<?php

namespace Container3wvxANR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTasksRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TasksRepository' shared autowired service.
     *
     * @return \App\Repository\TasksRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TasksRepository'] = new \App\Repository\TasksRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
