<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3wvxANR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3wvxANR/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container3wvxANR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container3wvxANR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container3wvxANR\App_KernelProdContainer([
    'container.build_hash' => '3wvxANR',
    'container.build_id' => '702ff88d',
    'container.build_time' => 1682473660,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3wvxANR');
